//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.4.4
//     from Assets/CharacterExample/Input/NPCInput.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @NPCInput : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @NPCInput()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""NPCInput"",
    ""maps"": [
        {
            ""name"": ""Movement"",
            ""id"": ""8ed774a0-09e6-4e6f-82aa-e6077e6c643f"",
            ""actions"": [
                {
                    ""name"": ""GoNext"",
                    ""type"": ""Button"",
                    ""id"": ""83937777-13e3-4492-ba12-965fe665ddd4"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""1135f9d2-9b5d-4af4-b860-010a5659d88b"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""GoNext"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Movement
        m_Movement = asset.FindActionMap("Movement", throwIfNotFound: true);
        m_Movement_GoNext = m_Movement.FindAction("GoNext", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Movement
    private readonly InputActionMap m_Movement;
    private IMovementActions m_MovementActionsCallbackInterface;
    private readonly InputAction m_Movement_GoNext;
    public struct MovementActions
    {
        private @NPCInput m_Wrapper;
        public MovementActions(@NPCInput wrapper) { m_Wrapper = wrapper; }
        public InputAction @GoNext => m_Wrapper.m_Movement_GoNext;
        public InputActionMap Get() { return m_Wrapper.m_Movement; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(MovementActions set) { return set.Get(); }
        public void SetCallbacks(IMovementActions instance)
        {
            if (m_Wrapper.m_MovementActionsCallbackInterface != null)
            {
                @GoNext.started -= m_Wrapper.m_MovementActionsCallbackInterface.OnGoNext;
                @GoNext.performed -= m_Wrapper.m_MovementActionsCallbackInterface.OnGoNext;
                @GoNext.canceled -= m_Wrapper.m_MovementActionsCallbackInterface.OnGoNext;
            }
            m_Wrapper.m_MovementActionsCallbackInterface = instance;
            if (instance != null)
            {
                @GoNext.started += instance.OnGoNext;
                @GoNext.performed += instance.OnGoNext;
                @GoNext.canceled += instance.OnGoNext;
            }
        }
    }
    public MovementActions @Movement => new MovementActions(this);
    public interface IMovementActions
    {
        void OnGoNext(InputAction.CallbackContext context);
    }
}
